- platform: template
  sensors:
    presence_chris:
      friendly_name: "Chris"
      device_class: presence
      value_template: "{{ is_state('device_tracker.chris_phone_gps', 'home') and is_state('device_tracker.smartstart_706837', 'home') }}"

    presence_melissa:
      friendly_name: "Melissa"
      device_class: presence
      value_template: "{{ is_state('device_tracker.melissa_phone_gps', 'home') and is_state('device_tracker.smartstart_90947', 'home') }}"

    presence_all:
      friendly_name: "Presence"
      device_class: presence
      value_template: "{{ is_state('binary_sensor.presence_chris', 'on') or is_state('binary_sensor.presence_melissa', 'on') or is_state('group.presence_shared', 'on') or is_state('input_boolean.guest_mode', 'on') or is_state('input_boolean.pool_party_mode', 'on') }}"
    
    upstairs_hall_motion:
      friendly_name: "Upstairs Hall Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.upstairs_hall_motion', '8') }}"

    master_bath_motion:
      friendly_name: "Master Bath Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.master_bath_motion', '8') }}"

    upstairs_bathroom_motion:
      friendly_name: "Upstairs Bathroom Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.upstairs_bathroom_wired_motion', '8') }}"

    mayson_in_bed:
      friendly_name: "Mayson is in Bed"
      entity_id: sensor.time, switch.maysons_fan, binary_sensor.mayson_in_bed
      icon_template: "{% if is_state('binary_sensor.mayson_in_bed', 'off') %}mdi:bed-empty{% else %}mdi:hotel{% endif %}"
      value_template: "{{ (now().hour >= 20 or now().hour < 7) and is_state('switch.maysons_fan', 'on') }}"

    master_bed_any:
      friendly_name: "Master any in Bed"
      entity_id: sensor.time, sensor.master_bed_count, binary_sensor.master_bed_any
      delay_on:
        minutes: 5
      delay_off:
        minutes: 10
      icon_template: "{% if is_state('binary_sensor.master_bed_any', 'off') %}mdi:bed-empty{% else %}mdi:hotel{% endif %}"
      value_template: "{{ (now().hour >= 20 or now().hour < 7) and states('sensor.master_bed_count')|int > 0 }}"

    master_bed_all:
      friendly_name: "Master all in Bed"
      entity_id: sensor.time, sensor.master_count, sensor.master_bed_count, binary_sensor.master_bed_all
      delay_on:
        minutes: 5
      delay_off:
        minutes: 10
      icon_template: "{% if is_state('binary_sensor.master_bed_all', 'off') %}mdi:bed-empty{% else %}mdi:hotel{% endif %}"
      value_template: "{{ (now().hour >= 20 or now().hour < 7) and states('sensor.master_count')|int > 0 and states('sensor.master_count') == states('sensor.master_bed_count') }}"

    upstairs_nest_protect:
      friendly_name: "Upstairs Nest Protect"
      entity_id: sensor.upstairs_nest_protect_color_status
      icon_template: "{{ 'mdi:smoke-detector' }}"
      value_template: "{{ is_state('sensor.upstairs_nest_protect_color_status', 'green') }}"

    basement_nest_protect:
      friendly_name: "Basment Nest Protect"
      entity_id: sensor.basement_nest_protect_color_status
      icon_template: "{{ 'mdi:smoke-detector' }}"
      value_template: "{{ is_state('sensor.basement_nest_protect_color_status', 'green') }}"

    time_to_upgrade:
      friendly_name: "Time to Upgrade Home Assistant"
      entity_id: sensor.current_version, sensor.latest_version
      icon_template: mdi:package-up
      value_template: '{{ states("sensor.latest_version").split(".")[1] | int - states("sensor.current_version").split(".")[1] | int > 1 }}'

    garage_fridge_temp_alert:
      friendly_name: "Garage Fridge Temperature Alert"
      entity_id: sensor.garage_fridge_rolling_average_temperature
      value_template: '{{ states("sensor.garage_fridge_rolling_average_temperature") | int < 33 or states("sensor.garage_fridge_rolling_average_temperature") | int > 42}}'

    garage_freezer_temp_alert:
      friendly_name: "Garage Freezer Temperature Alert"
      entity_id: sensor.garage_freezer_temp
      value_template: '{{ states("sensor.garage_freezer_temp") | int > 32}}'

    storage_alert:
      friendly_name: Storage Space is Low
      entity_id: sensor.disk_use_percent
      value_template: '{{ states("sensor.disk_use_percent") | int > 80}}'
