- platform: template
  sensors:
    presence_all:
      friendly_name: "Presence"
      device_class: presence
      entity_id: person.chris, person.melissa
      value_template: "{{ expand(['person.chris', 'person.melissa']) | selectattr('state', 'eq', 'home') | list | count > 0 }}"
    
    upstairs_hall_motion:
      friendly_name: "Upstairs Hall Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.upstairs_hall_motion', '8') }}"

    master_bath_motion:
      friendly_name: "Master Bath Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.master_bath_motion', '8') }}"

    upstairs_bathroom_motion:
      friendly_name: "Upstairs Bathroom Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.upstairs_bathroom_wired_motion', '8') }}"

    mayson_in_bed:
      friendly_name: "Mayson is in Bed"
      entity_id: sensor.time, switch.maysons_fan, binary_sensor.mayson_in_bed
      icon_template: "{% if is_state('binary_sensor.mayson_in_bed', 'off') %}mdi:bed-empty{% else %}mdi:bed{% endif %}"
      value_template: "{{ (now().hour >= 20 or now().hour < 7) and is_state('switch.maysons_fan', 'on') }}"

    master_bed_all:
      friendly_name: "Master all in Bed"
      entity_id: sensor.time, sensor.master_count, sensor.master_bed_count, binary_sensor.master_bed_all
      icon_template: "{% if is_state('binary_sensor.master_bed_all', 'off') %}mdi:bed-empty{% else %}mdi:bed{% endif %}"
      value_template: "{{ (now().hour >= 20 or now().hour < 7) and states('sensor.master_count')|int > 0 and states('sensor.master_count') <= states('sensor.master_bed_count') }}"

    upstairs_nest_protect:
      friendly_name: "Upstairs Nest Protect"
      entity_id: sensor.upstairs_nest_protect_color_status
      icon_template: "{{ 'mdi:smoke-detector' }}"
      value_template: "{{ is_state('sensor.upstairs_nest_protect_color_status', 'green') }}"

    basement_nest_protect:
      friendly_name: "Basment Nest Protect"
      entity_id: sensor.basement_nest_protect_color_status
      icon_template: "{{ 'mdi:smoke-detector' }}"
      value_template: "{{ is_state('sensor.basement_nest_protect_color_status', 'green') }}"

    time_to_upgrade:
      friendly_name: "Time to Upgrade Home Assistant"
      entity_id: sensor.current_version, sensor.latest_version
      icon_template: mdi:package-up
      value_template: '{{ states("sensor.latest_version").split(".")[1] | int - states("sensor.current_version").split(".")[1] | int > 1 }}'

    garage_fridge_temp_alert:
      friendly_name: "Garage Fridge Temperature Alert"
      entity_id: sensor.garage_fridge_rolling_average_temperature
      value_template: '{{ states("sensor.garage_fridge_rolling_average_temperature") | int < 33 or states("sensor.garage_fridge_rolling_average_temperature") | int > 42}}'

    garage_freezer_temp_alert:
      friendly_name: "Garage Freezer Temperature Alert"
      entity_id: sensor.garage_freezer_temp
      value_template: '{{ states("sensor.garage_freezer_temp") | int > 32}}'

    storage_alert:
      friendly_name: Storage Space is Low
      entity_id: sensor.disk_use_percent
      value_template: '{{ states("sensor.disk_use_percent") | int > 80}}'
    
    device_offline:
      friendly_name: One or More Devices are Offline
      value_template: "{{ expand(states.binary_sensor) | selectattr('attributes.device_class', 'eq', 'connectivity') | selectattr('state', 'eq', 'off') | list | length > 0 }}"

    robo_vac_status:
      friendly_name: Robo-Vac Status
      device_class: connectivity
      icon_template: mdi:robot-vacuum-variant
      entity_id: vacuum.neato
      value_template: "{{ not is_state('vacuum.neato', 'unavailable') }}"

    time_to_vacuum_main_floor:
      friendly_name: "Time to Vacuum the Main Floor"
      value_template: "{{ (as_timestamp(strptime(states('sensor.date_time'), '%Y-%m-%d, %H:%M')) - as_timestamp(state_attr('automation.vacuum_the_main_floor_at_night', 'last_triggered'))) / 60 /60 > 36 }}"

