homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 300
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant
  packages: !include_dir_named packages

# image_processing: !include image_processing.yaml

alert: !include alerts.yaml

alexa: !include alexa.yaml

api:

auth:

automation: !include_dir_merge_list automation/

binary_sensor: !include binary_sensors.yaml

browser_mod:
  prefix: "browser_"

# camera:
#   - platform: zoneminder

climate: !include climates.yaml

default_config:

device_tracker: !include device_trackers.yaml

discovery:

frontend:
  themes: !include_dir_merge_named themes

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

google_assistant: !include google_assistant.yaml

hacs:
  token: !secret hacs_token

history:
  exclude:
    domains:
    - automation
    - calendar
    - group
    - script
    - sun
    - updater
    - weather
    - zone
    - zwave

http: !include http.yaml

light: !include lights.yaml

logger:
  default: info
  logs:
    alexa_media.helpers: debug

lovelace:
  mode: yaml
  dashboards:
    lovelace-system-devices:
      title: System and Devices
      mode: yaml
      filename: ui-system-devices.yaml
      icon: mdi:server
      show_in_sidebar: true
      require_admin: true
    lovelace-presence-mode:
      title: Presence and Mode
      mode: yaml
      filename: ui-presence-mode.yaml
      icon: mdi:account-switch
      show_in_sidebar: true
      require_admin: true

media_player: !include media_players.yaml

notify: !include notifiers.yaml

python_script:

recorder:
  db_url: !secret recorder_db_url

remote: !include remotes.yaml

script: !include scripts.yaml

sensor: !include sensors.yaml

smartstart:
  username: !secret smartstart_username
  password: !secret smartstart_password

stream:

switch: !include switches.yaml

tts:
- platform: google_translate

updater:
  include_used_components: true

var:

weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key
    mode: daily

zone: !include zones.yaml

zwave: !include zwave.yaml
