- platform: tensorflow
  scan_interval: 10000
  source:
    - name: gate
      entity_id: camera.gate_2
  file_out:
    - "/config/www/cameras/gate_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"    
  model:
    graph: /config/tensorflow/frozen_inference_graph.pb
    area:
      top: .12
      bottom: 1
      left: 0
      right: 1
    categories:
      - person
