- platform: html5
  name: html5
  vapid_pub_key: !secret google_vapid_pub_key
  vapid_prv_key: !secret google_vapid_prv_key
  vapid_email: !secret google_email


- platform: nfandroidtv
  name: Family Room TV
  host: !secret firetv_family_room_ip
  fontsize: max
  color: red
  transparency: 50%


- platform: nfandroidtv
  name: Basement TV
  host: !secret firetv_basement_ip
  fontsize: max
  color: red
  transparency: 50%


- platform: nfandroidtv
  name: Master Bedroom TV
  host: 192.168.20.141
  fontsize: max
  color: red
  transparency: 50%
