- platform: time_date
  display_options:
  - 'time'
  - 'date'
  - 'date_time'
  - 'date_time_utc'

- platform: template
  sensors:
    day_night:
      friendly_name: "Day/Night"
      value_template: "{% if is_state('input_boolean.day_night', 'on') %}Day{%else%}Night{%endif%}"
      icon_template: "{% if is_state('input_boolean.day_night', 'on') %}mdi:weather-sunny{%else%}mdi:weather-night{%endif%}"
      
    maysons_battery:
      friendly_name: "Mayson's Sensor Battery"
      device_class: battery
      value_template: "{{ state_attr('zwave.maysons_sensor', 'battery_level') }}"
      
    upstairs_bathroom_battery:
      friendly_name: "Upstairs Bathroom Battery"
      device_class: battery
      value_template: "{{ state_attr('zwave.upstairs_bathroom_sensor', 'battery_level') }}"
      
    upstairs_bathroom_humidity_median:
      friendly_name: "Upstairs Bathroom Humidity Median"
      value_template: "{{ states.sensor.upstairs_bathroom_humidity_statistics.attributes.median }}"
      
    master_bath_humidity_median:
      friendly_name: "Master Bathroom Humidity Median"
      value_template: "{{ states.sensor.master_bathroom_humidity_statistics.attributes.median }}"

    master_bath_battery:
      friendly_name: "Master Bathroom Battery"
      device_class: battery
      value_template: "{{ state_attr('zwave.master_bath_sensor', 'battery_level') }}"

    master_count:
      friendly_name: "Master Count"
      entity_id: person.chris, person.melissa
      icon_template: "{% if states('sensor.master_count')|int == 2 %}mdi:account-multiple{% elif states('sensor.master_count')|int == 1 %}mdi:account{% else %}mdi:account-off{% endif %}"
      value_template: "{{ expand(['person.chris', 'person.melissa']) | selectattr('state', 'eq', 'home') | list | count }}"

- platform: statistics
  name: Upstairs Bathroom Humidity Statistics
  entity_id: sensor.upstairs_bathroom_humidity
  sampling_size: 240
  max_age:
    hours: 20

- platform: statistics
  name: Upstairs Bathroom Luminance Statistics
  entity_id: sensor.upstairs_bathroom_luminance
  sampling_size: 60
  max_age:
    minutes: 30

- platform: statistics
  name: Master Bathroom Humidity Statistics
  entity_id: sensor.master_bath_humidity
  sampling_size: 240
  max_age:
    hours: 20

- platform: statistics
  name: Master Bathroom Luminance Statistics
  entity_id: sensor.master_bath_luminance
  sampling_size: 60
  max_age:
    minutes: 30

- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: memory_use_percent
  - type: load_1m
  - type: load_5m
  - type: load_15m

- platform: version
- platform: version
  source: docker

- platform: cert_expiry
  host: !secret url_host

- platform: waze_travel_time
  name: Chris To Home
  origin: person.chris
  destination: zone.home
  region: US

- platform: waze_travel_time
  name: To Chris' Office
  origin: person.chris
  destination: zone.chris_work
  region: US

- platform: waze_travel_time
  name: Melissa To Home
  origin: person.melissa
  destination: zone.home
  region: US

- platform: waze_travel_time
  name: To Melissa's Office
  origin: person.melissa
  destination: zone.melissa_s_work_office
  region: US

- platform: waze_travel_time
  name: To Melissa's Southdale Office
  origin: person.melissa
  destination: zone.melissa_s_work_southdale
  region: US
