- platform: template
  switches:
    basement_stair_lights:
      friendly_name: 'Basement Stair Lights'
      value_template: "{{ is_state('switch.basement_stair_lights_top', 'on') }}"
      icon_template: "mdi:lightbulb"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.basement_stair_lights_top, switch.basement_stair_lights_bottom
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.basement_stair_lights_top, switch.basement_stair_lights_bottom

    basement_tv:
      friendly_name: 'Basement TV'
      value_template: "{{ is_state_attr('remote.basement_harmony_hub', 'current_activity', 'Basement TV - Home') or is_state_attr('remote.basement_harmony_hub', 'current_activity', 'Basement Live TV') or is_state_attr('remote.basement_harmony_hub', 'current_activity', 'Basement Netflix') }}"
      icon_template: "mdi:television"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.basement_harmony_hub
          activity: 'Basement TV - Home'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.basement_harmony_hub

    xbox:
      friendly_name: 'Xbox'
      value_template: "{{ is_state_attr('remote.basement_harmony_hub', 'current_activity', 'Xbox') }}"
      icon_template: "mdi:xbox"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.basement_harmony_hub
          activity: 'Xbox'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.basement_harmony_hub
