- platform: template
  switches:
    always_on:
      friendly_name: 'Always On Switch to Prevent Automation Errors'
      value_template: true
      turn_on:
      turn_off:

    always_off:
      friendly_name: 'Always Off Switch to Prevent Automation Errors'
      value_template: false
      turn_on:
      turn_off:

    basement_tv:
      friendly_name: 'Basement TV'
      value_template: "{{ is_state_attr('remote.basement_harmony_hub', 'current_activity', 'Basement TV - Home') or is_state_attr('remote.basement_harmony_hub', 'current_activity', 'Basement Live TV') or is_state_attr('remote.basement_harmony_hub', 'current_activity', 'Basement Netflix') }}"
      icon_template: "mdi:television"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.basement_harmony_hub
          activity: 'Basement TV - Home'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.basement_harmony_hub

    xbox:
      friendly_name: 'Xbox'
      value_template: "{{ is_state_attr('remote.basement_harmony_hub', 'current_activity', 'Xbox') }}"
      icon_template: "mdi:microsoft-xbox"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.basement_harmony_hub
          activity: 'Xbox'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.basement_harmony_hub
